[versions]
junit-jupiter = "5.11.1"
jackson-dataformat-toml = "2.18.3"
logback = "1.5.17"
[libraries]

junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit-jupiter" }
jackson-dataformat-toml = { module = "com.fasterxml.jackson.dataformat:jackson-dataformat-toml", version.ref = "jackson-dataformat-toml" }
logback = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
